# Generated by Django 5.2.11 on 2026-02-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
